apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/haq2682/argocd-gitops.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
