apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-nodejs-config
data:
  PORT: "3000"
  VERSION: "1.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-nodejs
  template:
    metadata:
      labels:
        app: argocd-nodejs
    spec:
      containers:
        - name: argocd-nodejs
          image: haq2682/argocd-nodejs:v1
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: argocd-nodejs-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-nodejs
spec:
  type: NodePort
  selector:
    app: argocd-nodejs
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080