apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "argocd-gitops"
      useAnnotations: true
