apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  writeBackConfig:
    method: "git:secret:argocd/git-creds"
    gitConfig:
      repository: "https://github.com/haq2682/argocd-gitops.git"
      branch: "main"
      writeBackTarget: "kustomization"

  applicationRefs:
    - namePattern: "argocd-gitops"
      images:
        - alias: "argocd-nodejs"
          imageName: "haq2682/argocd-nodejs:latest"
          commonUpdateSettings:
            updateStrategy: "digest"
      writeBackConfig:
        method: "git:secret:argocd/git-creds"
        gitConfig:
          writeBackTarget: "kustomization"
