apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - argocd.yaml
  - image-updater.yaml

images:
  - name: haq2682/argocd-nodejs
    newTag: latest
    digest: sha256:007c52b2ca2be38afb7828d4d8a1c0b35dcc98a1433418c89c92b81cd0f69582
