apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - argocd.yaml
  - image-updater.yaml

images:
  - name: haq2682/argocd-nodejs
    newTag: latest
    digest: sha256:87d74d6ff0d11de6255e613fbf5d0ebaf0eac6abfafc1cb25f1bafd634cb29b0
